spring:
  datasource:
    url: jdbc:mysql://localhost:3306/songtc?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: +yle9g_pps%J
    driver-class-name: com.mysql.cj.jdbc.Driver
